[package]
name = "networking-assignment"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "server"
path = "src/bin/server.rs"

[[bin]]
name = "client"
path = "src/bin/client.rs"

[[bin]]
name = "proxy"
path = "src/bin/proxy.rs"

[dependencies]
rand = "0.9.1"
